server:
  port: 8081

spring:
  application:
    name: Account-Service-Keycloak
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: account-service
            authorization-grant-type: authorization_code
            scope:
              - openid
              - email
              - profile
        provider:
          keycloak:
            issuer-uri: http://localhost:8085/realms/daara
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/daara
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

app:
  cors:
    allowed-origins: http://localhost:3000

logging:
  level:
    org.springframework.security: DEBUG
